// <auto-generated />
using System;
using Inmobiliaria.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inmobiliaria.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240708150125_Initial-Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inmobiliaria.Models.Inmueble", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("es_nuevo")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("fecha_construccion")
                        .HasColumnType("date");

                    b.Property<int>("metros")
                        .HasColumnType("int");

                    b.Property<double>("precio_base")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Inmuebles");

                    b.HasDiscriminator<string>("Tipo").HasValue("Inmueble");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Inmobiliaria.Models.Local", b =>
                {
                    b.HasBaseType("Inmobiliaria.Models.Inmueble");

                    b.Property<int>("nro_ventas")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Local");
                });

            modelBuilder.Entity("Inmobiliaria.Models.Piso", b =>
                {
                    b.HasBaseType("Inmobiliaria.Models.Inmueble");

                    b.Property<int>("planta")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Piso");
                });
#pragma warning restore 612, 618
        }
    }
}
