@ChatApp.Server_HostAddress = http://localhost:5000
@AccessToken = eyJhbGciOiJIUzI1NiIsImtpZCI6ImF0NFc3RkFnYlFDdGRlcC8iLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2NobnFpZGJzZ25uY2hlbmZ0eWxsLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJmYTFmYTc2My01MTM5LTQyYzMtYjg3OS03YjQ4OGZlMjA5MzEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzI2NjExMjE0LCJpYXQiOjE3MjY2MDc2MTQsImVtYWlsIjoidGVzdEBtYWlsdGVzdC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcyNjYwNzYxNH1dLCJzZXNzaW9uX2lkIjoiYTQ5NmU5YmUtYzc4OS00N2M5LTljNTctMjNiMGY2NzcwNGNjIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.8wp33Bexj2yfryk00dPzizo6ItiSMj926t5JWugSicg
GET {{ChatApp.Server_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{AccessToken}}
###
